//
//
// This file was automatically generated by shacl2code. DO NOT MANUALLY MODIFY IT
//
// SPDX-License-Identifier: Apache-2.0

package spdx_v3_0_1

type ErrorHandler interface {
    HandleError(error, Path)
}
