//
//
// This file was automatically generated by shacl2code. DO NOT MANUALLY MODIFY IT
//
// SPDX-License-Identifier: Apache-2.0

package spdx_v3_0_1

type LinkState struct {
    Objs map[string]SHACLObject
    Missing map[string]bool
}
